server:
  port: 9088

spring:
  application:
    name: user-auth-service
  datasource:
    url: jdbc:postgresql://localhost:55000/userdb
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000  # 1 hour
